server:
  port: 80


spring:
  datasource:
    hikari:
      dataSourceClassName: org.mariadb.jdbc.MariaDbDataSource
      jdbcUrl: jdbc:mysql://mint.szv2.nodes.wdksl.com:3306/schoolconnect?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: user
      password: 1234j
  mvc:
    view:
      suffix: .html
      prefix: /

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
