logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG


#spring:
#  security:
#    oauth2:
#
#      resourceserver:
#        jwt:
#          issuer-uri: https://auth.prod.schoolconnect.wdksl.com/issuer
wechat-mini-program:
  appid: wx47e3ac2e4d1e6488
  secret: 453f0f9d1cacb46f5bde7d23ad88b7fa


jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub

spring:
  profiles:
    #    active:
    include: dev