logging:
  level:
    root: INFO
    org.springframework.web: TRACE
    org.springframework.security: TRACE
#    org.springframework.boot.autoconfigure: DEBUG


#spring:
#  security:
#    oauth2:
#
#      resourceserver:
#        jwt:
#          issuer-uri: https://auth.prod.schoolconnect.wdksl.com/issuer
wechat-mini-program:
  appid: wx47e3ac2e4d1e6488
  secret: 453f0f9d1cacb46f5bde7d23ad88b7fa



spring:
  profiles:
    #    active:
    include: common
server:
  port: 80