server:
  port: 80
spring:
  config: # 又是一个新的写法
    import: classpath:application-common.yml
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://auth.prod.schoolconnect.wdksl.com/issuer



