#spring:
#  security:
#    oauth2:
#
#      resourceserver:
#        jwt:
#          issuer-uri: https://auth.prod.schoolconnect.wdksl.com/issuer
wechat-mini-program:
  appid: wx47e3ac2e4d1e6488
  secret: 453f0f9d1cacb46f5bde7d23ad88b7fa



spring:
#  profiles:
#    #    active: 不要用active 这样只会用这里的profile
#    include:
  config: # 超级新的写法
    import: classpath:application-common.yml

server:
  port: 80