server:
#  port: 8080
#  port: 80
  undertow:
    buffer-size: 1024
    direct-buffers: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.osmium.schoolconnect.backend
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

spring:

#  cache:
#    type: redis
#  main:
#    allow-bean-definition-overriding: true
#    lazy-initialization: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.147.59.95:13306/schoolconnect?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: user
    password: 1234j
    hikari:
      minimum-idle: 10
      idle-timeout: 30000
      maximum-pool-size: 20
      max-lifetime: 120000
      connection-timeout: 30000
#  data:
#    redis:
#      host:
#      port: 6379
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub