server:
  port: 8080
  servlet:
    context-path: /api

spring:
  cache:
    type: redis

  profiles:
    active: auth
  main:
    allow-bean-definition-overriding: true
    lazy-initialization: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mint.szv2.nodes.wdksl.com:3306/schoolconnect?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: user
    password: 1234j
    hikari:
      minimum-idle: 10
      idle-timeout: 30000
      maximum-pool-size: 20
      max-lifetime: 120000
      connection-timeout: 30000
  data:
    redis:
      host: mint.szv2.nodes.wdksl.com
      port: 6379
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true